### ISSUE TITLE
Remove dummy_ptr class

### ISSUE THREAD

**Issue by NotPrab** [DevT02/Junk-Remover#1]
super annoying

**Comment by DevT02** [comment]
I know what you are talking about. I'll attempt to work on a fix.

**Comment by DevT02** [comment]
Unfortunately, the reason why these classes are created is due to the flag `PreserveAll`, now I could remove this but it could throw a lot of errors in some programs. Maybe I will add an option for flags too? Idk

**Comment by NotPrab** [comment]
Yes that would be very apppricated.

**Comment by DevT02** [comment]
Let me know if you still have this issue in V1.51. Thanks.
