### ISSUE TITLE
Dont work!

### ISSUE THREAD

**Issue by ReallReaper** [DevT02/Junk-Remover#2]
I have this problem when i use the program
![error 1](https://user-images.githubusercontent.com/95001569/179853691-fc4a4e35-5b39-47ee-8d8f-a521ce8f9ef7.jpg)
 

- I have this in the same folder

- [x] dnlib.dll
- [x] Junk_Remover.exe.config
- [x] Junk_Remover.pdb
- [x] settings.txt
- [x] Junk_Remover.exe

- All files:
![all files](https://user-images.githubusercontent.com/95001569/179854009-41f7f9d3-11bc-4b28-a0e9-4fc5dce497c1.jpg)

**Comment by DevT02** [comment]
You're supposed to drag and drop file directly into the executable (aka you don't need to open anything)
